-- ============================================================================
-- Gastos fixos v2 — compromissos mensais
--
-- A tabela original guardava só (title, amount, due_day, is_auto, is_paid).
-- Faltava: chave de vínculo com o estabelecimento detectado, data de término
-- (parcelamento acaba), silenciamento sem hack de título "HIDDEN:" e pagamento
-- por mês (is_paid único não representa "paguei agosto, setembro está aberto").
--
-- Aditivo e idempotente: pode rodar em cima da tabela existente.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.fixed_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  due_day INTEGER,
  category TEXT DEFAULT 'Outros',
  is_auto BOOLEAN DEFAULT FALSE,
  is_paid BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Novas colunas -------------------------------------------------------------

-- MANUAL | SUBSCRIPTION | INSTALLMENT | VARIABLE_RECURRING
ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'MANUAL';

-- Chave normalizada do estabelecimento. Quando preenchida, esta linha
-- SUBSTITUI o item que o detector encontraria com a mesma chave — é assim que
-- você corrige um valor detectado errado sem perder o vínculo.
ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS merchant_key TEXT;

-- Conta de origem (opcional, só informativo)
ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS account_id TEXT;

-- Quando o compromisso deixa de existir (última parcela, contrato encerrado).
-- NULL = indeterminado.
ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS end_date DATE;

ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS installments_total INTEGER;

ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

-- Substitui o hack de gravar o título como 'HIDDEN:<chave>'
ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS is_muted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE public.fixed_expenses
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

DO $$
BEGIN
  ALTER TABLE public.fixed_expenses
    ADD CONSTRAINT fixed_expenses_kind_check
    CHECK (kind IN ('MANUAL', 'SUBSCRIPTION', 'INSTALLMENT', 'VARIABLE_RECURRING'));
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Uma chave de estabelecimento não pode ter dois vínculos ativos
CREATE UNIQUE INDEX IF NOT EXISTS fixed_expenses_merchant_key_uniq
  ON public.fixed_expenses (merchant_key)
  WHERE merchant_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS fixed_expenses_active_idx
  ON public.fixed_expenses (is_active, is_muted);

-- Migra as linhas do formato antigo 'HIDDEN:<chave>' -------------------------
UPDATE public.fixed_expenses
SET
  is_muted = TRUE,
  is_active = FALSE,
  merchant_key = COALESCE(merchant_key, LOWER(TRIM(REPLACE(title, 'HIDDEN:', ''))))
WHERE title LIKE 'HIDDEN:%'
  AND is_muted = FALSE;

-- ============================================================================
-- Pagamentos por período
--
-- Um compromisso detectado automaticamente não tem linha própria (é recalculado
-- a cada request), então o pagamento é marcado pela chave estável do detector:
--   'manual:12'  |  'rec:netflix'  |  'inst:carmo motos|62.00|6'
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.fixed_expense_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_key TEXT NOT NULL,
  period TEXT NOT NULL,            -- 'YYYY-MM'
  amount NUMERIC DEFAULT 0,
  paid_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fixed_expense_payments_period_format CHECK (period ~ '^\d{4}-\d{2}$'),
  CONSTRAINT fixed_expense_payments_uniq UNIQUE (expense_key, period)
);

CREATE INDEX IF NOT EXISTS fixed_expense_payments_period_idx
  ON public.fixed_expense_payments (period);

-- ============================================================================
-- Contas espelhadas
--
-- Alguns bancos exportam o mesmo cartão duas vezes com nomes diferentes — no
-- Inter, "THIAGO E SANTOS" e "GOLD" são o mesmo plástico. Cada cópia tem
-- account_id e transaction_id próprios (o upsert não resolve) e o ciclo de
-- fatura pode vir defasado em um mês, o que faz a dedupe por data falhar.
-- Marcar a cópia aqui é o que remove a duplicação na origem.
-- ============================================================================

ALTER TABLE public.accounts
  ADD COLUMN IF NOT EXISTS is_ignored BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS accounts_is_ignored_idx
  ON public.accounts (is_ignored);

-- Confira o que existe antes de marcar:
--   SELECT account_id, name, marketing_name, type, subtype,
--          credit_data->>'balance_due_date' AS vencimento,
--          (SELECT COUNT(*) FROM public.transactions t
--             WHERE t.account_id = a.account_id) AS lancamentos
--   FROM public.accounts a
--   WHERE type = 'CREDIT'
--   ORDER BY name;

-- Ignora o espelho "GOLD" do Inter, mantendo "THIAGO E SANTOS".
-- Ajuste o filtro se o nome no seu banco for diferente.
UPDATE public.accounts
SET is_ignored = TRUE
WHERE type = 'CREDIT'
  AND (name ILIKE '%GOLD%' OR marketing_name ILIKE '%GOLD%');

-- Para reverter:
--   UPDATE public.accounts SET is_ignored = FALSE WHERE is_ignored;

-- ============================================================================
-- Índices que o detector depende (varredura de 12 meses de histórico)
-- ============================================================================

CREATE INDEX IF NOT EXISTS transactions_date_type_idx
  ON public.transactions (date DESC, type);

CREATE INDEX IF NOT EXISTS transactions_account_date_idx
  ON public.transactions (account_id, date DESC);

-- ============================================================================
-- RLS
-- ============================================================================

ALTER TABLE public.fixed_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fixed_expense_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all" ON public.fixed_expenses;
CREATE POLICY "Allow all" ON public.fixed_expenses FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow all" ON public.fixed_expense_payments;
CREATE POLICY "Allow all" ON public.fixed_expense_payments FOR ALL USING (true);
